package com.sogoeslight.task

import com.sogoeslight.task.tree.RegressionTree

object Main extends App {

  //Data.prepare() // preparation stuff (lab 1)
  //DecisionTree.create() // decision tree generated by the id3 algorithm (lab 2)
  //LogisticRegression.calculate() // logistic regression with gradient descent (lab 3)
  //OneLayerPerceptrone.calculate(true) // one layer perceptrone (lab 4)
  //MultiLayerPerceptrone.calculate(showWeights = true)
  //Data_Akbilgic.prepare()
  //MultiLayerRegression.calculate(showWeights = false)
  RegressionTree.create()

}
